export const USER_SIGNUP_REQUEST = 'USER/SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER/SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER/SIGNUP_FAILURE';

export const USER_SIGNIN_REQUEST = 'USER/SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER/SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER/SIGNIN_FAILURE';

export const USER_SIGNOUT_REQUEST = 'USER/SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER/SIGNOUT_SUCCESS';

export const USER_UPDATE_REQUEST = 'USER/UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER/UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER/UPDATE_FAILURE';
