export const USER_SIGNUP_REQUEST = 'USER/SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER/SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER/SIGNUP_FAILURE';

export const USER_SIGNIN_REQUEST = 'USER/SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER/SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER/SIGNIN_FAILURE';

export const USER_SIGNOUT_REQUEST = 'USER/SIGNOUT_REQUEST';
export const USER_SIGNOUT_SUCCESS = 'USER/SIGNOUT_SUCCESS';

export const USER_UPDATE_EMAIL_REQUEST = 'USER/UPDATE_EMAIL_REQUEST';
export const USER_UPDATE_EMAIL_SUCCESS = 'USER/UPDATE_EMAIL_SUCCESS';
export const USER_UPDATE_EMAIL_FAILURE = 'USER/UPDATE_EMAIL_FAILURE';

export const USER_UPDATE_FIRST_NAME_REQUEST = 'USER/UPDATE_FIRST_NAME_REQUEST';
export const USER_UPDATE_FIRST_NAME_SUCCESS = 'USER/UPDATE_FIRST_NAME_SUCCESS';
export const USER_UPDATE_FIRST_NAME_FAILURE = 'USER/UPDATE_FIRST_NAME_FAILURE';

export const USER_UPDATE_LAST_NAME_REQUEST = 'USER/UPDATE_LAST_NAME_REQUEST';
export const USER_UPDATE_LAST_NAME_SUCCESS = 'USER/UPDATE_LAST_NAME_SUCCESS';
export const USER_UPDATE_LAST_NAME_FAILURE = 'USER/UPDATE_LAST_NAME_FAILURE';
